# Generated by Django 3.1.4 on 2021-02-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_teammember_tech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='project',
        ),
        migrations.AddField(
            model_name='tech',
            name='projects',
            field=models.ManyToManyField(related_name='techs', to='portfolio_app.Project'),
        ),
    ]
