# Generated by Django 3.1.4 on 2021-02-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_auto_20210222_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='icon_img_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
